### ISSUE TITLE
Integrate Flatpak updates in update tools

### ISSUE THREAD

**Issue by plata** [endeavouros-team/PKGBUILDS#258]
Currently, updating Arch and AUR packages works nicely through eos-update-notifier. However, Flatpak updates are not integrated here.

Workarounds:
- KDE Discover (doesn't support AUR)
- Pamac
- Bauh
- manually via `flatpak update`

I'm aware that there is `AdditionalEosUpdater`. The `eos-update-notifier` [Discovery page](https://discovery.endeavouros.com/endeavouros-tools/endeavouros-update-notifier/2021/03/) even mentions:
> call an external program for other updating (e.g. updating flatpaks)

Nevertheless, it is not really clear how this shall work (see e.g. https://forum.endeavouros.com/t/eos-update-notifier-and-flatpak/20520). From #80, it seems that [UpdateInTerminal](https://github.com/endeavouros-team/PKGBUILDS/blob/master/eos-bash-shared/UpdateInTerminal) must be changed as well.

Goal:
- minimum: update [Flatpak](https://discovery.endeavouros.com/applications/flatpak-enabling-and-application-management/2021/03/) and [eos-update-notifier](https://discovery.endeavouros.com/endeavouros-tools/endeavouros-update-notifier/2021/03/) Discovery pages and describe in detail how to enable Flatpak updates.
- best: treat Flatpak similarly to AUR (e.g. add `CheckFlatpakUpdates`  to `eos-update-notifier`).

**Comment by manuel-192** [comment]
An update notifier was originally meant for users that are not familiar with the ways Arch and EndeavourOS should be updated. Updates come at least daily and sometimes more, so generally an update notifier is not much needed. User should simply run any of the available updating commands (e.g. `yay`), and almost every time there are updates.

If user wants to use more software sources like flatpak, then the easiest way to do that is to write a small function to the `~/.bashrc` file which runs both yay and the flatpak update commands.

So this is one of the reasons why we are not considering making eos-update-notifier (and friends) more complex than what they already are. Running your own function (or script) is a very easy way to achieve the best solution.

**Comment by plata** [comment]
I understand the reasoning.

Is there a Discovery page explaining this and the "canonical" way how to update EOS? I got the impression that many people think `eos-update-notifier` is the way. If I understand you correctly, that's not really the case. However, the presentation of `eos-update-notifier` in the welcome dialog and in Discovery seems to suggest exactly that.

**Comment by dalto8** [comment]
There is no canonical way to update EOS.  You can do it however you like.
* You can use the button in the Welcome App
* The script UpdateInTerminal
* Using the command `yay`
* Any other way you prefer to update your system

**Comment by plata** [comment]
I still would appreciate a Discovery page which explains this because I  feel like it's not particularly clear (especially for new users). Describing best practices or even just a set of possibilities would be very helpful.

**Comment by manuel-192** [comment]
Best practices depends greatly on the user and what she/he wants to do. That's why it is not easy to describe "general" best practices.

EndeavourOS is based on Arch, so the Arch way to update with `sudo pacman-Syu` is great and reliable.
EndeavourOS has some additions for certain situations, like the `yay` AUR helper, in case you have installed also AUR packages.

These two programs are capable of handling all repository and AUR packages, and thus it is strongly recommended that a user *knows* how to use them.

UpdateInTerminal is a wrapper for pacman and yay, and as the name suggests, it is a (simple) way to update the system without having to remember pacman or yay options.

As said already earlier, eos-update-notifier is mostly meant for users new to EndeavourOS, and users who like to be notified of updates regularly. Of course the update schedule can be adjusted to reasonable default if user wants.

As @dalto mentioned, it is up to you to decide how to update your system, and which software sources to use.

Note that on the EndeavourOS forum (https://forum.endeavouros.com/) we have has several discussions related to this too, with several different aspects presented. Feel free to join the forum (if you are not there already)!
